services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    image: loopcore-app:latest
    container_name: loopcore-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - loopcore-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - functions

  functions:
    build: 
      context: ./functions
      dockerfile: Dockerfile
      target: runner
    image: loopcore-functions:latest
    container_name: loopcore-functions
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - loopcore-network

networks:
  loopcore-network:
    name: loopcore-network
    driver: bridge