version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  functions:
    build: 
      context: .
      dockerfile: functions/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped